name: Run Delete Rooms

on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  build:
    name: Delete Rooms
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: "curl -X DELETE -H 'Authorization: ${{ secrets.DELETE_KEY }}' 'https://neo-letter-fastify.vercel.app/api/rooms'"